tasks:
  - name: setup-environment
    init: |
      cd /workspace
      chmod +x setup-local.sh
      ./setup-local.sh
      cd $THEIA_WORKSPACE_ROOT

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-python.python
    - ms-vscode.vscode-json
    - bradlc.vscode-tailwindcss
