tasks:
  - name: setup-environment
    init: |
      cd /workspace
      chmod +x .devcontainer/setup.sh
      ./.devcontainer/setup.sh
      cd $THEIA_WORKSPACE_ROOT

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-python.python
    - ms-vscode.vscode-json
    - bradlc.vscode-tailwindcss
    - ms-vscode.vscode-typescript-next
    - esbenp.prettier-vscode
    - ms-vscode.vscode-eslint
